# -*- coding: utf-8 -*-
"""XAI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_YajVEC_tmtxj6U3tSG6TeQz51UcLxM
"""

!pip install pytorch-lightning==1.9.5
!pip install pytorch-forecasting --upgrade

!git clone https://github.com/sahandyousefi/credit-fraud-detection.git

!pip install torch shap captum pandas-ta

!pip install kaggle

from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive/')

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/AIML Dataset.csv')
print(df.shape)
print(df.head())

print(df.columns.tolist())

# Sample 20% to avoid RAM crash
df = df.sample(frac=0.2, random_state=42)
df = df.sort_values('step').reset_index(drop=True)

print("Sample size:", df.shape)
print("Fraud cases:", df['isFraud'].sum())

df['balanceChangeOrig'] = df['newbalanceOrig'] - df['oldbalanceOrg']
df['balanceChangeDest'] = df['newbalanceDest'] - df['oldbalanceDest']
df['amountToOldBalanceRatio'] = df['amount'] / (df['oldbalanceOrg'] + 1)
df['originEmptied'] = (df['newbalanceOrig'] == 0).astype(int)
df['destIsNew'] = (df['oldbalanceDest'] == 0).astype(int)
df['type_encoded'] = df['type'].map({'PAYMENT':0,'TRANSFER':1,'CASH_OUT':2,'DEBIT':3,'CASH_IN':4})
df['isHighRiskType'] = df['type'].isin(['TRANSFER','CASH_OUT']).astype(int)
df['hour'] = df['step'] % 24
df['day'] = df['step'] // 24

df.to_csv('/content/drive/MyDrive/processed_fraud_data.csv', index=False)
print("Done!", df.columns.tolist())

# Prepare Dataset for for LSTM

from sklearn.preprocessing import MinMaxScaler

# Select Features

features= ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
            'oldbalanceDest', 'newbalanceDest', 'balanceChangeOrig',
            'balanceChangeDest', 'amountToOldBalanceRatio',
            'originEmptied', 'destIsNew', 'type_encoded',
            'isHighRiskType', 'hour', 'day'

]


target="isFraud"

X=df[features].values
y=df[target].values

#scale
scaler=MinMaxScaler()
X_scaled=scaler.fit_transform(X)

print("X shape:", X_scaled.shape)
print("y shape:", y.shape)
print("Fraud cases:", y.sum())

"""## Handling imbalanced dataset"""

from sklearn.utils.class_weight import compute_class_weight

# Compute class weights
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y),
    y=y
)

class_weight_dict = {0: class_weights[0], 1: class_weights[1]}
print("Class weights:", class_weight_dict)

"""## Splitting Dataset"""

from sklearn.model_selection import train_test_split

# Train/test split - time based
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, shuffle=False
)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# Convert to tensors
X_train_t = torch.FloatTensor(X_train).unsqueeze(1)
X_test_t = torch.FloatTensor(X_test).unsqueeze(1)
y_train_t = torch.FloatTensor(y_train)
y_test_t = torch.FloatTensor(y_test)

# DataLoader
train_dataset = TensorDataset(X_train_t, y_train_t)
train_loader = DataLoader(train_dataset, batch_size=512, shuffle=False)

# LSTM Model
class FraudLSTM(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2):
        super(FraudLSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out, _ = self.lstm(x)
        out = self.fc(out[:, -1, :])
        return self.sigmoid(out)

model = FraudLSTM(input_size=15)
print(model)

# Remove sigmoid from model (BCEWithLogitsLoss handles it)
import torch
import torch.nn as nn

# Define the device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class FraudLSTM(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2):
        super(FraudLSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

model = FraudLSTM(input_size=15).to(device)

# Higher weight penalty
pos_weight = torch.tensor([500.0]).to(device)
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

# Train
epochs = 10
for epoch in range(epochs):
    model.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        output = model(X_batch).squeeze()
        loss = criterion(output, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(train_loader):.4f}")

"""## Evaluation"""

from sklearn.metrics import classification_report, roc_auc_score

model.eval()
with torch.no_grad():
    output = model(X_test_t.to(device)).squeeze()
    predictions = torch.sigmoid(output)
    predictions = (predictions > 0.5).cpu().numpy()

print(classification_report(y_test, predictions))
print("AUC-ROC:", roc_auc_score(y_test, predictions))

"""### Recall of 0.38 means we're missing 62% of frauds"""

epochs = 10
for epoch in range(epochs):
    model.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        output = model(X_batch).squeeze()
        loss = criterion(output, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(train_loader):.4f}")

model.eval()
with torch.no_grad():
    output = model(X_test_t.to(device)).squeeze()
    predictions = torch.sigmoid(output)
    predictions = (predictions > 0.5).cpu().numpy()

print(classification_report(y_test, predictions))
print("AUC-ROC:", roc_auc_score(y_test, predictions))

"""# Save the Model"""

# Save model to Google Drive
torch.save(model.state_dict(), '/content/drive/MyDrive/lstm_fraud_model.pth')
print("Model saved!")

"""# Model 2: TFT"""

!pip install pytorch-forecasting

"""## Data Prepration for TFT"""

from pytorch_forecasting import TemporalFusionTransformer, TimeSeriesDataSet
from pytorch_forecasting.metrics import CrossEntropy
import pandas as pd

# Prepare dataframe for TFT
df_tft = pd.DataFrame(X_scaled, columns=features)
df_tft['isFraud'] = y.astype(str)
df_tft['time_idx'] = range(len(df_tft))
df_tft['group'] = '0'  # single group

print(df_tft.head())
print(df_tft.shape)

torch.save({
    'model_state_dict': model.state_dict(),
    'X_scaled': X_scaled,
    'y': y,
    'X_train': X_train,
    'X_test': X_test,
    'y_train': y_train,
    'y_test': y_test,
}, '/content/drive/MyDrive/checkpoint.pth')
print("Checkpoint saved! ✅")

class FraudTransformer(nn.Module):
    def __init__(self, input_size, nhead=1, num_layers=2):
        super(FraudTransformer, self).__init__()
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=input_size, nhead=nhead, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc = nn.Linear(input_size, 1)

    def forward(self, x):
        out = self.transformer(x)
        return self.fc(out[:, -1, :])

model_transformer = FraudTransformer(input_size=15).to(device)

criterion_t = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([500.0]).to(device))
optimizer_t = torch.optim.Adam(model_transformer.parameters(), lr=0.0001)

epochs = 10
for epoch in range(epochs):
    model_transformer.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer_t.zero_grad()
        output = model_transformer(X_batch).squeeze()
        loss = criterion_t(output, y_batch)
        loss.backward()
        optimizer_t.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(train_loader):.4f}")

model_transformer.eval()
with torch.no_grad():
    output = model_transformer(X_test_t.to(device)).squeeze()
    predictions_t = torch.sigmoid(output)
    predictions_t = (predictions_t > 0.5).cpu().numpy()

print(classification_report(y_test, predictions_t))
print("AUC-ROC:", roc_auc_score(y_test, predictions_t))

torch.save(model_transformer.state_dict(),
           '/content/drive/MyDrive/transformer_fraud_model.pth')
print("Transformer saved! ")

torch.save({
    'lstm_model': model.state_dict(),
    'transformer_model': model_transformer.state_dict(),
    'X_scaled': X_scaled,
    'y': y,
    'X_train': X_train,
    'X_test': X_test,
    'y_train': y_train,
    'y_test': y_test,
}, '/content/drive/MyDrive/full_checkpoint.pth')
print("Everything saved!")

checkpoint = torch.load('/content/drive/MyDrive/full_checkpoint.pth',
                        weights_only=False)
X_scaled = checkpoint['X_scaled']
y = checkpoint['y']
X_train = checkpoint['X_train']
X_test = checkpoint['X_test']
y_train = checkpoint['y_train']
y_test = checkpoint['y_test']

print("Everything restored!")

import torch.nn as nn

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Rebuild LSTM
class FraudLSTM(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2):
        super(FraudLSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

# Rebuild Transformer
class FraudTransformer(nn.Module):
    def __init__(self, input_size, nhead=1, num_layers=2):
        super(FraudTransformer, self).__init__()
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=input_size, nhead=nhead, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc = nn.Linear(input_size, 1)

    def forward(self, x):
        out = self.transformer(x)
        return self.fc(out[:, -1, :])

# Load saved weights
model = FraudLSTM(input_size=15).to(device)
model.load_state_dict(checkpoint['lstm_model'])

model_transformer = FraudTransformer(input_size=15).to(device)
model_transformer.load_state_dict(checkpoint['transformer_model'])

print("Models restored!")

import torch
from torch.utils.data import DataLoader, TensorDataset

X_train_t = torch.FloatTensor(X_train).unsqueeze(1)
X_test_t = torch.FloatTensor(X_test).unsqueeze(1)
y_train_t = torch.FloatTensor(y_train)
y_test_t = torch.FloatTensor(y_test)

train_dataset = TensorDataset(X_train_t, y_train_t)
train_loader = DataLoader(train_dataset, batch_size=512, shuffle=False)

print("Tensors ready!")

"""# SHAP Prepration"""

!pip install shap
import shap
import numpy as np

# Use small sample for SHAP (computationally expensive)
X_shap = X_test[:500]
X_shap_t = torch.FloatTensor(X_shap).unsqueeze(1).to(device)

# SHAP wrapper for LSTM
def lstm_predict(x):
    model.eval()
    with torch.no_grad():
        x_t = torch.FloatTensor(x).unsqueeze(1).to(device)
        output = torch.sigmoid(model(x_t))
        return output.cpu().numpy()

# Use KernelExplainer
explainer = shap.KernelExplainer(lstm_predict, X_test[:100])
print("SHAP Explainer ready!")

# Compute SHAP values
print("Computing SHAP values...")
shap_values = explainer.shap_values(X_shap[:100])
print("SHAP values computed!")
print("Shape:", shap_values.shape)

import matplotlib.pyplot as plt

features = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
            'oldbalanceDest', 'newbalanceDest', 'balanceChangeOrig',
            'balanceChangeDest', 'amountToOldBalanceRatio',
            'originEmptied', 'destIsNew', 'type_encoded',
            'isHighRiskType', 'hour', 'day']

# Summary plot
shap_values_2d = shap_values[:, :, 0]
shap.summary_plot(shap_values_2d, X_shap[:100], feature_names=features)

def transformer_predict(x):
    model_transformer.eval()
    with torch.no_grad():
        x_t = torch.FloatTensor(x).unsqueeze(1).to(device)
        output = torch.sigmoid(model_transformer(x_t))
        return output.cpu().numpy()

explainer_t = shap.KernelExplainer(transformer_predict, X_test[:100])
shap_values_t = explainer_t.shap_values(X_shap[:100])
print("Transformer SHAP done!")

# Transformer SHAP summary plot
shap_values_t_2d = shap_values_t[:, :, 0]
shap.summary_plot(shap_values_t_2d, X_shap[:100], feature_names=features)

"""# Temporal Consistency Metric"""

# Split test data into time windows
n_windows = 5
window_size = len(X_shap) // n_windows

temporal_shap = []
for i in range(n_windows):
    start = i * window_size
    end = start + window_size
    window_shap = explainer.shap_values(X_shap[start:end])
    temporal_shap.append(window_shap[:, :, 0])
    print(f"Window {i+1}/{n_windows} done!")

print("Temporal SHAP computed!")

"""## Temporal Consistency Metric Computation"""

import numpy as np
from scipy.stats import spearmanr

def temporal_consistency_score(temporal_shap_values):
    """
    Novel Metric: Measures how stable feature attributions
    are across consecutive time windows.
    Score of 1.0 = perfectly consistent
    Score of 0.0 = completely inconsistent
    """
    n_windows = len(temporal_shap_values)
    correlations = []

    for i in range(n_windows - 1):
        # Mean SHAP per feature for each window
        window_i = np.abs(temporal_shap_values[i]).mean(axis=0)
        window_j = np.abs(temporal_shap_values[i+1]).mean(axis=0)

        # Spearman correlation between consecutive windows
        corr, _ = spearmanr(window_i, window_j)
        correlations.append(corr)

    return np.mean(correlations), correlations

# Compute for LSTM
lstm_score, lstm_corrs = temporal_consistency_score(temporal_shap)
print(f"LSTM Temporal Consistency Score: {lstm_score:.4f}")
print(f"Window correlations: {[round(c,4) for c in lstm_corrs]}")

"""# Computes the same fot transformer"""

# Compute Transformer temporal SHAP
temporal_shap_t = []
for i in range(n_windows):
    start = i * window_size
    end = start + window_size
    window_shap = explainer_t.shap_values(X_shap[start:end])
    temporal_shap_t.append(window_shap[:, :, 0])
    print(f"Window {i+1}/{n_windows} done!")

# Compute score
transformer_score, transformer_corrs = temporal_consistency_score(temporal_shap_t)
print(f"Transformer Temporal Consistency Score: {transformer_score:.4f}")
print(f"Window correlations: {[round(c,4) for c in transformer_corrs]}")

"""# SHAP for 2000"""

# Recompute with 2000 samples
X_shap = X_test[:2000]

explainer = shap.KernelExplainer(lstm_predict, X_test[:200])
print("Computing SHAP values for 2000 samples - will take ~10 minutes...")
shap_values = explainer.shap_values(X_shap)
print("SHAP values computed!")
print("Shape:", shap_values.shape)

# Summary plot with 2000 samples
shap_values_2d = shap_values[:, :, 0]
shap.summary_plot(shap_values_2d, X_shap, feature_names=features)

"""# Recompute Temporal Consistency"""

n_windows = 5
window_size = len(X_shap) // n_windows

temporal_shap = []
for i in range(n_windows):
    start = i * window_size
    end = start + window_size
    window_shap = explainer.shap_values(X_shap[start:end])
    temporal_shap.append(window_shap[:, :, 0])
    print(f"Window {i+1}/{n_windows} done!")

lstm_score, lstm_corrs = temporal_consistency_score(temporal_shap)
print(f"LSTM Temporal Consistency Score: {lstm_score:.4f}")
print(f"Window correlations: {[round(c,4) for c in lstm_corrs]}")

"""# Transformer Sample"""

explainer_t = shap.KernelExplainer(transformer_predict, X_test[:200])
print("Computing Transformer SHAP for 2000 samples...")
shap_values_t = explainer_t.shap_values(X_shap)
print("Transformer SHAP computed!")

"""## Temporal Consistency for Transformer Computation"""

temporal_shap_t = []
for i in range(n_windows):
    start = i * window_size
    end = start + window_size
    window_shap = explainer_t.shap_values(X_shap[start:end])
    temporal_shap_t.append(window_shap[:, :, 0])
    print(f"Window {i+1}/{n_windows} done!")

transformer_score, transformer_corrs = temporal_consistency_score(temporal_shap_t)
print(f"Transformer Temporal Consistency Score: {transformer_score:.4f}")
print(f"Window correlations: {[round(c,4) for c in transformer_corrs]}")

import numpy as np

np.save('/content/drive/MyDrive/shap_lstm_2000.npy', shap_values)
np.save('/content/drive/MyDrive/shap_transformer_2000.npy', shap_values_t)

print("All SHAP values saved!")

"""## Retrain XGBoost"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import numpy as np
from sklearn.model_selection import train_test_split

checkpoint = torch.load('/content/drive/MyDrive/full_checkpoint.pth',
                        weights_only=False)
X_scaled = checkpoint['X_scaled']
y = checkpoint['y']
X_train = checkpoint['X_train']
X_test = checkpoint['X_test']
y_train = checkpoint['y_train']
y_test = checkpoint['y_test']

print("Everything restored!")
print("Train size:", X_train.shape)
print("Test size:", X_test.shape)
print("Fraud in test:", y_test.sum())

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score

# Train XGBoost with balanced weights
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print("scale_pos_weight:", scale_pos_weight)

xgb_model = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    n_estimators=100,
    random_state=42,
    eval_metric='auc'
)

xgb_model.fit(X_train, y_train)
print("XGBoost trained!")

# Evaluate XGBoost
y_pred_xgb = xgb_model.predict(X_test)
y_pred_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_xgb))
print("AUC-ROC:", roc_auc_score(y_test, y_pred_proba_xgb))

"""# Adding SHAP to XGBoost"""

import shap

explainer_xgb = shap.TreeExplainer(xgb_model)
shap_values_xgb = explainer_xgb.shap_values(X_test[:2000])
print("XGBoost SHAP done!")

features = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
            'oldbalanceDest', 'newbalanceDest', 'balanceChangeOrig',
            'balanceChangeDest', 'amountToOldBalanceRatio',
            'originEmptied', 'destIsNew', 'type_encoded',
            'isHighRiskType', 'hour', 'day']

shap.summary_plot(shap_values_xgb, X_test[:2000], feature_names=features)

"""# Temporal Consistency for XGBoost"""

from scipy.stats import spearmanr
import numpy as np

def temporal_consistency_score(temporal_shap_values):
    n_windows = len(temporal_shap_values)
    correlations = []

    for i in range(n_windows - 1):
        # For TreeExplainer, shap_values can be a list if it's a multi-output model
        # Here we assume it's a single-output model, so we take the first element if it's a list
        if isinstance(temporal_shap_values[i], list):
            window_i = np.abs(temporal_shap_values[i][0]).mean(axis=0)
            window_j = np.abs(temporal_shap_values[i+1][0]).mean(axis=0)
        else:
            window_i = np.abs(temporal_shap_values[i]).mean(axis=0)
            window_j = np.abs(temporal_shap_values[i+1]).mean(axis=0)
        corr, _ = spearmanr(window_i, window_j)
        correlations.append(corr)

    return np.mean(correlations), correlations

n_windows = 5
window_size = 2000 // n_windows

temporal_shap_xgb = []
for i in range(n_windows):
    start = i * window_size
    end = start + window_size
    # explainer_xgb.shap_values might return a list for multiclass, so handle that
    window_shap = explainer_xgb.shap_values(X_test[start:end])
    temporal_shap_xgb.append(window_shap)
    print(f"Window {i+1}/{n_windows} done!")

xgb_score, xgb_corrs = temporal_consistency_score(temporal_shap_xgb)
print(f"XGBoost Temporal Consistency Score: {xgb_score:.4f}")
print(f"Window correlations: {[round(c,4) for c in xgb_corrs]}")

n_windows = 5
window_size = 2000 // n_windows

temporal_shap_xgb = []
for i in range(n_windows):
    start = i * window_size
    end = start + window_size
    window_shap = explainer_xgb.shap_values(X_test[start:end])
    temporal_shap_xgb.append(window_shap)
    print(f"Window {i+1}/{n_windows} done!")

xgb_score, xgb_corrs = temporal_consistency_score(temporal_shap_xgb)
print(f"XGBoost Temporal Consistency Score: {xgb_score:.4f}")

"""# All Result Saving"""

np.save('/content/drive/MyDrive/shap_xgb_2000.npy',
        explainer_xgb.shap_values(X_test[:2000]))
print("All results saved!")

import matplotlib.pyplot as plt
import shap
import numpy as np

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

features = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
            'oldbalanceDest', 'newbalanceDest', 'balanceChangeOrig',
            'balanceChangeDest', 'amountToOldBalanceRatio',
            'originEmptied', 'destIsNew', 'type_encoded',
            'isHighRiskType', 'hour', 'day']

# Figure 1 - XGBoost SHAP
shap.summary_plot(shap_values_xgb, X_test[:2000],
                  feature_names=features, show=False)
plt.savefig('/content/drive/MyDrive/fig1_xgboost_shap.png',
            dpi=300, bbox_inches='tight')
plt.close()

# Figure 2 - LSTM SHAP
shap_values_2d = shap_values[:, :, 0]
shap.summary_plot(shap_values_2d, X_shap,
                  feature_names=features, show=False)
plt.savefig('/content/drive/MyDrive/fig2_lstm_shap.png',
            dpi=300, bbox_inches='tight')
plt.close()

# Figure 3 - Transformer SHAP
shap_values_t_2d = shap_values_t[:, :, 0]
shap.summary_plot(shap_values_t_2d, X_shap,
                  feature_names=features, show=False)
plt.savefig('/content/drive/MyDrive/fig3_transformer_shap.png',
            dpi=300, bbox_inches='tight')
plt.close()

# Figure 4 - TCM Bar Chart
models = ['XGBoost', 'LSTM', 'Transformer']
tcm_scores = [0.9991, 0.9982, 0.9946]
colors = ['#2196F3', '#4CAF50', '#FF9800']
plt.figure(figsize=(8, 5))
bars = plt.bar(models, tcm_scores, color=colors, width=0.5)
plt.ylim(0.99, 1.0)
plt.ylabel('TCM Score')
plt.title('Temporal Consistency Metric by Model')
for bar, score in zip(bars, tcm_scores):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.0001,
             f'{score}', ha='center', fontsize=11)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/fig4_tcm_chart.png',
            dpi=300, bbox_inches='tight')
plt.close()

# Figure 5 - Window Correlation Line Plot
windows = [1, 2, 3, 4]
xgb_corrs = [1.0, 1.0, 0.9964, 0.9998]
lstm_corrs = [1.0, 1.0, 0.9964, 0.9964]
trans_corrs = [0.9928, 0.9892, 0.9748, 0.9784]
plt.figure(figsize=(8, 5))
plt.plot(windows, xgb_corrs, 'b-o', label='XGBoost')
plt.plot(windows, lstm_corrs, 'g-s', label='LSTM')
plt.plot(windows, trans_corrs, 'r-^', label='Transformer')
plt.xlabel('Consecutive Window Pair')
plt.ylabel('Spearman Correlation')
plt.title('Temporal Consistency Across Time Windows')
plt.legend()
plt.ylim(0.97, 1.01)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/fig5_window_correlation.png',
            dpi=300, bbox_inches='tight')
plt.close()

print("All figures saved!")

